<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="obj/SMUCommands.extracted.cs" />
    <Compile Include="../../Universal x86 Tuning Utility/Scripts/Misc/AutoOcDiagnostics.cs" Link="AutoOcDiagnostics.cs" />
  </ItemGroup>
</Project>
